owner: tttylerr # GitHub username
repo: uptime # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
assignees: # Users to assign downtime issues (optional)
  - GamingLizard9
  - WitherBuilder13
status-website: # Status website (optional)
  repo: /repo # Custom domain CNAME
  name: Upptime # Status website title
